### ISSUE TITLE
News Page: Create several news items to test different cases

### ISSUE THREAD

**Issue by tnabtaf** [conda-incubator/conda-dot-org#10]
## Description

The [news page](https://hackmd.io/ljHIgPXqQuimhTmQOPeh9g#News) will be our first "[index](https://hackmd.io/ljHIgPXqQuimhTmQOPeh9g#Feed--Index-pages)" page.  These pages list items of a particular type (e.g., news, blog, events, etc.).

We need news items that test the different cases for the news index page. All of these items should also include the metadata we deem important from this issue:

- #8 

## Tasks

- [x] Create a news item that resides within this website. (See [here](https://hackmd.io/-HIbt-UkROmifc7fDBMijw).)
- [x] Create a news item that points to an item in another website.
- [ ] Create two news items with the same date.
- [ ] Create a news item with a date in the future (and decide what should be done with it).

**Comment by tnabtaf** [comment]
A first batch of 3 news items was added in PR #29.
