### ISSUE TITLE
News Page: Implement final design

### ISSUE THREAD

**Issue by tnabtaf** [conda-incubator/conda-dot-org#12]
## Description

The [news page](https://hackmd.io/ljHIgPXqQuimhTmQOPeh9g#News) will be our first "[index](https://hackmd.io/ljHIgPXqQuimhTmQOPeh9g#Feed--Index-pages)" page.  These pages list items of a particular type (e.g., news, blog, events, etc.).

The implementation team needs to write the code that generates the news item index page, using the metadata (#8) in the news items (#10) to generate the design (#11) that the design team proposes.

## Tasks

- [ ] Using the final design from the design team, implement the news page using the site style sheet.
- [ ] Submit this for review via a pull request and iterate until everyone is satisfied.
- [ ] Also create the front page news layout.

**Comment by travishathaway** [comment]
Closing because we have decided not to have a separate news page. It is now rolled up into the blog.
