### ISSUE TITLE
Create a base site style sheet and decide CSS framework

### ISSUE THREAD

**Issue by travishathaway** [conda-incubator/conda-dot-org#13]
## Description

This style sheet will form the base that we use for conda.org. This style sheet should define the following:

- Fonts
  - Header tag fonts
  - Paragraph/body tag fonts
- Colors (make sure these are accessible by using a tool like [this](https://webaim.org/resources/contrastchecker/))
  - Background color
  - Primary/secondary

Most other decisions (e.g. margin, padding, etc.) should be left up to the CSS framework we decide on using (e.g. Bootstrap). Please decide on and add this CSS framework to the site while working on this issue.

I believe Docusaurus comes with some defaults for CSS, but it may be worth investigating whether we want to use another CSS framework entirely. This should be possible to override.

## Tasks

- [ ] Determine a CSS framework
  - [ ] Add and configure this to the project if not using the Docusaurus default
- [ ] Create a style sheet defining the fonts we want to use as well as our color pallet
  - [ ] Add and configure any extra font files you decide on

**Comment by kirtanchandak** [comment]
Can I work on this issue, I am planning to use Tailwind CSS for this.

**Comment by travishathaway** [comment]
Hi @kirtanchandak ,

Thank you for your interest. I would advise joining our Slack channel to get a faster response! 😅 Please read more here:

https://conda.discourse.group/t/conda-org-is-coming-and-we-want-your-help/99
