### ISSUE TITLE
Back port relevant blog posts from anaconda.com 

### ISSUE THREAD

**Issue by travishathaway** [conda-incubator/conda-dot-org#132]
## Description

We currently have a lot of interesting and well written blog posts on [Anaconda.com blog](https://anaconda.com/blog). We want to see which ones would be good candidates to port over.

These blog posts should:

- Be relevant to conda, conda-build or other related tools
- Have proper permissions to be transferred over (we should reach out to the authors to get approval)

## Tasks

- [ ] Create a list of possible blog articles to port over and list them here in a comment.
- [ ] Get permission to port these over from the authors.
- [ ] Create new pull requests to add these blog articles (one pull request per article).

**Comment by vasvi-sood** [comment]
@travishathaway I would like to work on this issue

**Comment by vasvi-sood** [comment]
These are the blog posts I think could be migrated here.  Please review them and let me know what you think.
1. [New! CVE Association for Conda-Forge Packages Helps Secure Your Software Supply Chain](https://www.anaconda.com/blog/new-cve-association-for-conda-forge-packages-helps-secure-your-software-supply-chain)
2. [ New Release: Anaconda Distribution 2023.03](https://www.anaconda.com/blog/new-release-anaconda-distribution-2023-03)
3. [Four Open-Source Projects and the Anaconda Maintainers Who Love Them](https://www.anaconda.com/blog/four-open-source-projects-and-the-anaconda-maintainers-who-love-them)
4. [Code in the Cloud With Anaconda—for Free!](https://www.anaconda.com/blog/code-in-the-cloud-with-anaconda-for-free)
5. [New Year, New You: What Will You Learn Next?](https://www.anaconda.com/blog/what-will-you-learn-next)
6. [2022: An Anaconda Year in Review](https://www.anaconda.com/blog/2022-an-anaconda-year-in-review)
7. [Introducing a New Plugin Mechanism for conda](https://www.anaconda.com/blog/introducing-a-new-plugin-mechanism-for-conda)
8. [Conda Is Fast Now. Like, Really Fast](https://www.anaconda.com/blog/conda-is-fast-now)
9. [Anaconda and Oracle Bring Secure Open-Source Software to OCI](https://www.anaconda.com/blog/anaconda-and-oracle-bring-secure-open-source-software-to-oci)
10. [Introducing Data Science Training and Cloud-Hosted Notebooks From Anaconda](https://www.anaconda.com/blog/introducing-python-training-and-cloud-hosted-notebooks-from-anaconda)
11. [A Faster Solver for Conda: Libmamba](https://www.anaconda.com/blog/a-faster-conda-for-a-growing-community)
12. [Keeping your Conda Environments Safe and Secure with your Anaconda Nucleus Account](https://www.anaconda.com/blog/keeping-your-conda-environments-safe-and-secure-with-your-anaconda-nucleus-account)

**Comment by tnabtaf** [comment]
Hi @vasvi-sood, 

Thanks for creating this list.  I have some suggestions about not reproducing some of them on the conda.org site.  This is mainly related to maintaining the distinction between Conda and Anaconda, a message that we constantly struggle with.

Here are my suggestions:

**Port** to conda.org:

* [Introducing a New Plugin Mechanism for conda](https://www.anaconda.com/blog/introducing-a-new-plugin-mechanism-for-conda)
* [Conda Is Fast Now. Like, Really Fast](https://www.anaconda.com/blog/conda-is-fast-now)
* [A Faster Solver for Conda: Libmamba](https://www.anaconda.com/blog/a-faster-conda-for-a-growing-community)

**Do not** (or so I say!) port to conda.org

* ~~[Code in the Cloud With Anaconda—for Free!](https://www.anaconda.com/blog/code-in-the-cloud-with-anaconda-for-free)~~
* ~~[2022: An Anaconda Year in Review](https://www.anaconda.com/blog/2022-an-anaconda-year-in-review)~~
* ~~[Introducing Data Science Training and Cloud-Hosted Notebooks From Anaconda](https://www.anaconda.com/blog/introducing-python-training-and-cloud-hosted-notebooks-from-anaconda)~~

These don't have enough about conda. I don't believe they belong on conda.org.

After that it gets even more complicated

* ~~[New! CVE Association for Conda-Forge Packages Helps Secure Your Software Supply Chain](https://www.anaconda.com/blog/new-cve-association-for-conda-forge-packages-helps-secure-your-software-supply-chain)~~
    * This service is available to Anaconda's paying customers.  We don't yet have a policy on how to handle paid features from companies.  This feature is useful, but the policy lags behind.  Also if we did port it, I would suggest just a short post on conda.org that points to the full post at Anaconda.
    * Recommendation: don't post anything now.  Anyone else have opinions?

* ~~[Anaconda and Oracle Bring Secure Open-Source Software to OCI](https://www.anaconda.com/blog/anaconda-and-oracle-bring-secure-open-source-software-to-oci)~~
    * Same as previous one.  We need clearer policies about paid features.


* [New Release: Anaconda Distribution 2023.03](https://www.anaconda.com/blog/new-release-anaconda-distribution-2023-03)
    * I don't have a clear opinion on this one.  Anyone?

* ~~[Four Open-Source Projects and the Anaconda Maintainers Who Love Them](https://www.anaconda.com/blog/four-open-source-projects-and-the-anaconda-maintainers-who-love-them)~~
    * This is fundamentally an Anaconda blog post.  I can imagine a short post on conda.org that talks about Jannis's comments and then points to the full blog post.
    * Recommendation: Someone (Vasvi you clearly **have not** volunteered for this) write a short post that highlights Jannis's part and then points to the full post on Anaconda.

* ~~[New Year, New You: What Will You Learn Next?](https://www.anaconda.com/blog/what-will-you-learn-next)~~
    * This links to several course at Anaconda.  The top two are directly relevant to conda, and they are free to access.  However, I don't think the whole post is relevant.  
    * Recommendation: Someone write a short post linking to the two relevant courses.  We could ask Jess H to do this.

* [Keeping your Conda Environments Safe and Secure with your Anaconda Nucleus Account](https://www.anaconda.com/blog/keeping-your-conda-environments-safe-and-secure-with-your-anaconda-nucleus-account)
    * This is a free and valuable service.  But I think we just want to summarize it and then link to the full post on Anaconda.  
    * Recommendation: Someone write a short post summarizing the original post, and then link to it.

Hope this helps, and I apologize for the long response.

**Comment by kenodegard** [comment]
I concur with @tnabtaf's thoughts, anything we back port must be entirely conda and should likely avoid any mention of Anaconda.

Personally I would include stuff even older than 3 years. The prior maintenance team left lots of great posts many of which cover info, knowledge, and other tidbits that are poorly documented elsewhere, e.g.:
- https://www.anaconda.com/blog/what-conda-canary
- https://www.anaconda.com/blog/preview-new-features-conda-canary
- https://www.anaconda.com/blog/condas-new-noarch-packages
- https://www.anaconda.com/blog/conda-4-6-release
- https://www.anaconda.com/blog/how-we-made-conda-faster-4-7
- https://www.anaconda.com/blog/using-pip-in-a-conda-environment
- https://www.anaconda.com/blog/moving-conda-environments

**Comment by vasvi-sood** [comment]
@tnabtaf Thank you for your insightful review. I understand from your comment above that not all the posts that I mentioned, fully capture the essence of conda and its functionality. For the posts that you mentioned that should be ported, I would like to personally reach out to the authors, seeking their permission to port their content to conda.org. Additionally, I would like  to write a concise post focusing on Jannis's comment about conda, as featured in the article [Four Open-Source Projects and the Anaconda Maintainers Who Love Them](https://www.anaconda.com/blog/four-open-source-projects-and-the-anaconda-maintainers-who-love-them).

**Comment by tnabtaf** [comment]
That sounds great @vasvi-sood. Thanks again for doing this.

**Comment by vasvi-sood** [comment]
@beeankha can I port the article [Introducing a New Plugin Mechanism for conda (https://www.anaconda.com/blog/introducing-a-new-plugin-mechanism-for-conda) over to conda.org?

**Comment by vasvi-sood** [comment]
@LtDan33 can I port over your article [Conda Is Fast Now. Like, Really Fast](https://www.anaconda.com/blog/conda-is-fast-now) to conda.org?

**Comment by vasvi-sood** [comment]
@jezdez @wolfv @FFY00 @trallard can I port this over [A Faster Solver for Conda: Libmamba](https://www.anaconda.com/blog/a-faster-conda-for-a-growing-community)?

**Comment by vasvi-sood** [comment]
@jezdez can I write a short blog post about your comment on conda mentioned in this article [A Faster Solver for Conda: Libmamba](https://www.anaconda.com/blog/a-faster-conda-for-a-growing-community)?
