### ISSUE TITLE
Create a site style guide

### ISSUE THREAD

**Issue by travishathaway** [conda-incubator/conda-dot-org#14]
## Description

After completing this issue, we will have a site style guide that will contain a color palette and a set of fonts that will inform the rest of the design work for conda.org. The goal of this issue is to pick the colors and fonts we will use for the website and to accordingly update the CSS files for the website.

Items we need:

- Primary color (obviously green, but which green? 😅 🟢 )
- Secondary color (basically a contrast color to our primary)
- Fonts
  - Header
  - Body/paragraph
- Background color (probably white, but again which one? 

The color palette should be accessible. So please check it with a tool similar to this: https://webaim.org/resources/contrastchecker/

## Tasks

- [x] Pick a font combination (header and body text)
- [x] Create a site color palette and update the site `custom.css` with this
  - [x] Primary and secondary colors should be updated accordingly

**Comment by jaimergp** [comment]
From @isabela-pf's proposal at https://github.com/conda-incubator/conda-dot-org/issues/1#issuecomment-1231395782:

> Green and a little bit of pattern using the repeated ‘C’s. Header text is [League Mono](https://github.com/theleagueof/league-mono) bold, and body text is [Junction](https://github.com/theleagueof/junction). Colors are #3DB049, #454545, #F5F5F5, and #FCFCFC for the background. I’ve shown it on all the options described in the above comment.

I added some variants on the prototype now but it's far from perfect.

**Comment by travishathaway** [comment]
We are now voting on fonts! Please go checkout these open pull requests:

- https://github.com/conda-incubator/conda-dot-org/pull/64
- https://github.com/conda-incubator/conda-dot-org/pull/65
- https://github.com/conda-incubator/conda-dot-org/pull/69

**Comment by Asmit2952** [comment]
> We are now voting on fonts! Please go checkout these open pull requests:
> 
> * [Font combo one: Lato and OpenSans #64](https://github.com/conda-incubator/conda-dot-org/pull/64)
> * [Font combo two: Oswald and Source Sans Pro #65](https://github.com/conda-incubator/conda-dot-org/pull/65)
> * [Font combo three: Nunito and OpenSans #69](https://github.com/conda-incubator/conda-dot-org/pull/69)

#69 👍🏻

**Comment by travishathaway** [comment]
Thanks for the recommendation @Asmit2952 

I was poking around with the accessibility tool to see how our primary color choice scores. Unfortunately, this does not have the needed contrast to be completely accessible (#43B02A vs #FFFFFF).

I propose that we just pick a darker version of the primary color we currently have. A color that gives a better score is #348721
