### ISSUE TITLE
Make documentation links prominent

### ISSUE THREAD

**Issue by tnabtaf** [conda-incubator/conda-dot-org#171]
## Description

If people landing at conda.org and are looking for conda ecosystem tool documentation, it can be hard to find.  Creating this issue to get us to think about how we might want to make these links easy to find.

## Tasks

- [ ] Decide on implementation.
- [ ] Decide on what tools to include.  Is there any hierarchy of tools, where some are more prominently featured than others?
- [ ] Add links to site.

## Discussion

The [conda discourse site](https://conda.discourse.group/) links to tool doc sites using a menu in the top menu bar of the site.  It links to 6 specific tools and then also links to the conda and conda-incubator pages in GitHub for other things. This would be one way to implement this.
