### ISSUE TITLE
Package Search: Integrated search of any registered conda channel (long term solution)

### ISSUE THREAD

**Issue by tnabtaf** [conda-incubator/conda-dot-org#173]
## Description

As described in #172, a large number of unsuccessful searches on conda.org are for package names.  We aren't currently addressing this use case.  Issue #172 is about easy, short term solutions to help our users find packages.

This issue proposes that we will need a better solution, and one that will likely take some engineering effort.

In an ideal world people could do package searches on conda.org.  They could enter a package name and the site would show them which channels the package is available on.  There could be two searches on the site (web site, package) or it could be an integrated search that returns everything, possibly under different tabs for web site and packages.

Ideally there would also be a mechanism for anyone to register a conda channel / request that a conda channel be added to the search.

## Tasks

- [ ] Design a package search solution that can search multiple channels
- [ ] Implement design
- [ ] Spread the word.
- [ ] Maybe: Implement a way for people to request adding conda channels to the search.
