### ISSUE TITLE
Improve community section with "Conda Ecosystem Explained" content

### ISSUE THREAD

**Issue by jezdez** [conda-incubator/conda-dot-org#200]
## Description

Following the work on #198, it's worth porting the information into the community section under https://conda.org/community, since most of this is ever-green content.

## Tasks

- [ ] Review the final draft of #198
- [ ] Port ever-green content to community section
- [ ] Expand on
  - [ ] governance policy overview
  - [ ] CEP process for evolving the conda stack
  - [ ] incubation for innovating new ideas
