### ISSUE TITLE
Site Search: Implement search

### ISSUE THREAD

**Issue by tnabtaf** [conda-incubator/conda-dot-org#21]
## Description

Implement site search functionality using the technology decided on in issue #20.  If we support searching multiple sites, then also include the sites from issue #19 in the search results.

## Tasks

- [ ] Implement site search proof of concept
- [ ] Ask entire team on slack to test it.
- [ ] Refine results accordingly.

**Comment by Avik-creator** [comment]
Is this issue still opened? And ca someone please explain me what to do in it?
