### ISSUE TITLE
Contributing HowTo(s) Framework

### ISSUE THREAD

**Issue by tnabtaf** [conda-incubator/conda-dot-org#23]
## Description

We need how to contribute documentation.  This would cover how to create content, and how to improve and contribute to the site in general.  This documentation could reside just in GitHub, anchored at or entirely in CONTRIBUTING.md, or in the published site, or both, depending on the HowTo content.

## Tasks

- [ ] Decide on structure and home for the contributing documentation.  Post that decision and structure to this issue.
- [ ] Publish a first version in the location decided on in the first task.  
  - [ ] Include basic content about creating news items in the first version.  This will include a discussion of whatever page metadata we decide on for news pages (see #8).
