### ISSUE TITLE
Code of conduct

### ISSUE THREAD

**Issue by barabo** [conda-incubator/conda-dot-org#30]
## Description

Decide on a code of conduct strategy and add it to the site.

## Tasks

- [ ] Discuss options for a Code of Conduct in a community meeting
- [ ] Decide on a strategy
- [ ] Add it to the site

**Comment by jezdez** [comment]
As a project in the conda incubator the site and repo fall under the Conda Code of Conduct, as defined in the [conda governance policy](https://github.com/conda-incubator/governance#code-of-conduct). Is there anything else missing?

**Comment by tnabtaf** [comment]
The CoC should be prominently featured on the web site.  I also lean towards having the web site be it's primary home.
