### ISSUE TITLE
Blog: Implement final design

### ISSUE THREAD

**Issue by travishathaway** [conda-incubator/conda-dot-org#32]
## Description

This is a task for collecting all the work on creating the layouts for the blog pages. This work also covers other places on the website where a blog teasers will be shown (e.g. the front page).

## Tasks

- [ ] Create a layout for the main blog page; this will include creating layouts for the individual blog list items on this page.
- [ ] Create a layout for the a blog page
- [ ] Create a layout for blog teasers (i.e. last two blog posts) and then put this on the front page

**Comment by travishathaway** [comment]
For now, we are going with the default layout of the blog pages that Docusaurus provides.
