### ISSUE TITLE
Add CSS and JS Linter

### ISSUE THREAD

**Issue by travishathaway** [conda-incubator/conda-dot-org#34]
## Description

In order to ensure a consistent coding style, we will add both a CSS and JS linter to our website. This will be run via GitHub actions for each pull request. We will not be using a tool like pre-commit because we want to make it as easy as possible to contribute.

## Tasks

- [x] Decide on JS linter and choose reasonable rules (stick mostly with defaults; check out other projects for inspiration)
- [x] Decide on CSS linter and choose reasonable rules
- [x] Add a GitHub action to run these checks for each new pull request
