### ISSUE TITLE
Frequently Asked Questions

### ISSUE THREAD

**Issue by kathatherine** [conda-incubator/conda-dot-org#40]
## Description

An FAQ needs to be added to the Docs section of the website. There will be an initial push of the following answered questions:

- What is conda-forge?
- What is a feedstock?
- How can I search for packages?
- What is the difference between `conda create` and `conda env create`?
- Why should I use conda and not just install everything with pip?
- Why is it not recommended to install everything into the `base` environment?
- How do I submit a blog post to conda.org?
- I see a problem with the website. How do I report it?

After that initial merge, this ticket will be an umbrella issue for other questions, as we fill in the FAQ more. If you want to add a question to the FAQ and this ticket is still open, please create a separate issue and link it in the checklist below.

## Tasks

- [x] https://github.com/conda-incubator/conda-dot-org/issues/45
- [x] https://github.com/conda-incubator/conda-dot-org/issues/46
- [x] https://github.com/conda-incubator/conda-dot-org/issues/47
- [x] https://github.com/conda-incubator/conda-dot-org/issues/48
- [x] https://github.com/conda-incubator/conda-dot-org/issues/49
- [x] https://github.com/conda-incubator/conda-dot-org/issues/50
- [ ] https://github.com/conda-incubator/conda-dot-org/issues/51
- [x] https://github.com/conda-incubator/conda-dot-org/issues/52
- [x] https://github.com/conda-incubator/conda-dot-org/issues/53
- [x] https://github.com/conda-incubator/conda-dot-org/issues/54
- [x] https://github.com/conda-incubator/conda-dot-org/issues/55

**Comment by kathatherine** [comment]
Some suggestions I got when I asked a few conda users at Anaconda:

- What is the difference between `conda create` and `conda env create`?
- How can I search for packages?
- Why can't conda find this package that I know exists?

**Comment by vasvi-sood** [comment]
If no one is working on this I would like to take up this issue @kathatherine  @beeankha

**Comment by beeankha** [comment]
@vasvi-sood that sounds good! Please make sure to create new issues for each new FAQ question and assign yourself to any that you will be working on.

**Comment by tnabtaf** [comment]
Hi folks, any opinion on closing this issue?

**Comment by tnabtaf** [comment]
Closing.  The FAQ has been online for months.
