### ISSUE TITLE
News - our first index page.

### ISSUE THREAD

**Issue by tnabtaf** [conda-incubator/conda-dot-org#5]
## Description

The website will feature several index/feed pages that summarize a particular type of post.  This includes a news page, and events page, blog posts and so on.  These index pages will be built programmatically from metadata about these news items / events / blog posts, that is stored in the web site source.  The index pages should be able to link to items that are native to this website, as well as to items that live on other sites.

I propose a news page as our first index page.

## Tasks

This will require

- [ ] Negotiate metadata content and format between implementation and content teams.
- [ ] Implementation team decides on file/directory structure of news items: Are news items stored in their own directory/place, or are they stored in the same place as blog posts, events, etc, and identified through tags?  Other options?
- [ ] Content team creates several news items, including at least
  - [ ] An item that lives on this site
  - [ ] An item that lives on another site
- [ ] Design team decides on high level presentation: A table, a list, cards, what?
- [ ] Implementation team writes the code that generates the index page.
- [ ] Design and Implementation teams iterate a few times.

The code to generate the page can be used as a model to create other index pages.

## See

* [Feed/Index page description](https://hackmd.io/ljHIgPXqQuimhTmQOPeh9g#Feed--Index-pages)

**Comment by tnabtaf** [comment]
This issue has been split up into many smaller issues.  See issues #8, #9, #10, #11, #12.
