### ISSUE TITLE
Blog Post: Publish late 2022 Conda survey

### ISSUE THREAD

**Issue by tnabtaf** [conda-incubator/conda-dot-org#58]
## Description

Anaconda [ran a community survey in November 2022](https://conda.discourse.group/t/tell-us-how-you-use-conda/113).  That announcement says:

> The results of the survey will be summarized and published, and then used to help guide future directions for conda.

We haven't done that yet, and it seems to me this would be a great blog post.  Around the same time, the Python community also published the [results of the Python Packaging User Survey](https://drive.google.com/file/d/1U5d5SiXLVkzDpS0i1dJIA4Hu5Qg704T9/view). It might be good to include relevant insights from that too.

It's also a great time to work out best practices for putting images inline in pages on the site.  I suggest we use this blog post to work out those best practices.

## Tasks

- [x] Submit a PR with an initial blog post draft.  This first draft will have text and images in it. The images may be poorly handled, and they may be handled in different ways throughout the document. (See PR #66 )
- [x] Work with the Implementation Team to figure out the best ways to include different types of images inline, inside of website pages.
- [x] Prepare the blog post for final publication 
- [x] Publish it.  (Note this could happen before the site itself is up.  We could update the publication date when the site is actually launched.
