### ISSUE TITLE
Home Page 

### ISSUE THREAD

**Issue by tnabtaf** [conda-incubator/conda-dot-org#6]
## Description

The home page is special. It unifies the site and makes it easy for people to quickly find what they are looking for.  It won't look like content or index pages.  This is a mixture of design, content and technology to implement, but I suspect it is mostly Design.

## Tasks

- [ ] Design Team: draw up proposals for layouts
- [ ] Design Team: Pick a proposal to implement
- [ ] Implementation: Work with Design team to implement that proposal.
- [ ] Content Team: Replace boilerplate text or refine text on home page.

**Comment by tnabtaf** [comment]
Split this into smaller issues #16, #17, #18.
