### ISSUE TITLE
Implement Search

### ISSUE THREAD

**Issue by tnabtaf** [conda-incubator/conda-dot-org#7]
## Description

The website needs a search function.  Ideally that search function would also search an identified list of other conda-related sites as well.  See [here](https://galaxyproject.org/search/?q=conda#gsc.tab=0&gsc.q=conda&gsc.page=1) for how Galaxy does this with [Google Programmable Engine Search](https://programmablesearchengine.google.com/about/).

## Tasks

- [ ] Content Team: Identify list of sites / subsites / URLs to include
- [ ] Implementation Team: Identify search technology to use
- [ ] Implementation Team: Implement proof of concept
- [ ] Implementation and Design Teams: iterate over presentation 

## See

* [Search Notes](https://hackmd.io/p3ybOVoBR6OKq-yhNUwffA#Search)

**Comment by tnabtaf** [comment]
Split this issue into 3 smaller ones: #19, #20, and #21.
