### ISSUE TITLE
Front page tweaks and improvements

### ISSUE THREAD

**Issue by travishathaway** [conda-incubator/conda-dot-org#77]
## Description

This issue is a follow up to the work initially done by @asmitbm in:

- https://github.com/conda-incubator/conda-dot-org/issues/17

## Tasks

- [x] Adjust the size of the tagline text
- [x] Add image to the first featured blog post
- [x] Adjust the layout of blog cards on the front page, adding icons to the date
