### ISSUE TITLE
Change top level "Docs" menu to "Learn"

### ISSUE THREAD

**Issue by travishathaway** [conda-incubator/conda-dot-org#78]
## Description

conda.org is no documentation website. Therefore, we want to change the "Docs" menu item to "Learn" instead. This will be an area for us to educate our users on the conda ecosystem.

## Tasks

- [ ] Change the top level menu item from "Docs" to "Learn"
- [ ] Make sure other menus that reference "Docs" have been updated too
- [ ] Change "Get Started" button text on front page to say "Learn More"
