### ISSUE TITLE
Update/Complete the "What is conda?" Info Page

### ISSUE THREAD

**Issue by beeankha** [conda-incubator/conda-dot-org#80]
## Description

The ["Learn"](https://github.com/conda-incubator/conda-dot-org/issues/78) page opens with a page that asks "What is conda?". This intro page is still a WIP which needs to be fully written out and polished.

## Tasks

- [ ] Write out copy for the page
- [ ] Reformat/update the page with the new text
- [ ] _[optional]_ Move it all to the [home page](https://conda-dot-org-previews.netlify.app/)

**Comment by travishathaway** [comment]
@beeankha, I'm going to close this issue considering that we have removed this page. Please re-open if you disagree.
