### ISSUE TITLE
News Page: Decide on file/directory structure for news items and other items that feed index pages

### ISSUE THREAD

**Issue by tnabtaf** [conda-incubator/conda-dot-org#9]
## Description

The [news page](https://hackmd.io/ljHIgPXqQuimhTmQOPeh9g#News) will be our first "[index](https://hackmd.io/ljHIgPXqQuimhTmQOPeh9g#Feed--Index-pages)" page.  These pages list items of a particular type (e.g., news, blog, events, etc.).

This issues asks: How are news items stored in the directory structure?  Are news items stored in their own directory/place, or are they stored in the same place as blog posts, events, etc, and identified through tags? Is there a directory hierarchy within news items (e.g., each year gets a new subdirectory?

Are there naming conventions for files/directories containing news items?  Should it be 

* `something-descriptive`
* `YYYY[-MM[-DD]]-something-descriptive`
* or something else?

## Tasks

- [ ] Create a proposal for how this should be laid out and get a yes or no approval from the implementation team (either in slack or during our regular meetings).
- [ ] ~Decide on file/directory structure, and the use of tags (or not) to define different content types (news, blog, event, etc).~
- [ ] Store this proposal in an accessible place (preferably [our HackMD workspace](https://hackmd.io/team/conda-dot-org?nav=overview)) so that we will be able to reference it later.
- [ ] Post a link to this proposal on this issue

**Comment by tnabtaf** [comment]
PR #29 is a particular implementation of of this structure, modeled on the implementation used in the blog posts.  However, it is just a suggestion.

**Comment by travishathaway** [comment]
I will be closing this for now as we have rolled the news items into the blog. We can consider re-opening this in the future if we ever decide to split out news items into their own content type.
